export const DEVICES = [
  { name: 'Your phone', ip: '192.168.1.20', port: 51820, mapped: 62001, mac: '02:00:00:00:01:20' },
  { name: 'Work laptop', ip: '192.168.1.21', port: 51820, mapped: 62002, mac: '02:00:00:00:01:21' },
  { name: 'Tablet', ip: '192.168.1.22', port: 53000, mapped: 62003, mac: '02:00:00:00:01:22' },
];
export const NODES = [
  {
    name: 'Your device',
    short: 'TEL AVIV',
    lat: 32.09,
    lon: 34.78,
    h: 0.045,
    ip: '192.168.1.20',
    role: 'Application + socket',
    text: 'The application encrypts a message for the recipient. The operating system associates its socket with a local IP, port and transport protocol. For an off-subnet destination, it sends a frame to the gateway MAC, not the distant server MAC.',
  },
  {
    name: 'Building gateway',
    short: 'NAT / PAT',
    lat: 32.09,
    lon: 34.78,
    h: 0.17,
    ip: '203.0.113.10',
    role: 'Router + NAT + stateful firewall',
    text: 'LAN interface 192.168.1.1/24. Source NAT replaces a private socket with a public IP and mapped port. The reverse entry translates replies. IP and transport checksums are updated. A stateful firewall can reject traffic that does not match an allowed flow.',
  },
  {
    name: 'Israeli ISP',
    short: 'ISP · IL',
    lat: 33.5,
    lon: 30,
    h: 0.07,
    ip: '203.0.113.1',
    role: 'Provider edge router',
    text: 'A destination-based forwarding-table lookup selects the next hop, usually by longest prefix match. The ISP routes the packet without terminating its TCP or decrypting its TLS payload.',
  },
  {
    name: 'European transit',
    short: 'MARSEILLE',
    lat: 43.3,
    lon: 5.37,
    h: 0.055,
    ip: '198.51.100.1',
    role: 'Peering / backbone router',
    text: 'Autonomous systems exchange reachability using BGP. Forwarding happens in routers using installed routes. The path is policy-driven, not necessarily the shortest geographic path.',
  },
  {
    name: 'Atlantic backbone',
    short: 'ATLANTIC',
    lat: 44,
    lon: -35,
    h: 0.035,
    ip: '198.51.100.2',
    role: 'Aggregate transit hop',
    text: 'This point stands for a transit router along a subsea-fiber path. A cable itself does not have a packet-routing IP address. Many physical and router hops are compressed into this view.',
  },
  {
    name: 'US backbone',
    short: 'US TRANSIT',
    lat: 39,
    lon: -87,
    h: 0.065,
    ip: '198.51.100.3',
    role: 'Backbone router',
    text: 'The packet continues across the United States toward the relay address. The recipient’s IP is not the destination of the sender-to-server TCP connection.',
  },
  {
    name: 'Secure application relay',
    short: 'US WEST RELAY',
    lat: 45.6,
    lon: -121.2,
    h: 0.14,
    ip: '198.51.100.40',
    role: 'TLS endpoint / TURN relay',
    text: 'This illustrative US West relay is deliberately beyond New York so the two network legs are visible. In the TCP model it terminates connection A and its TLS session, then forwards still end-to-end-encrypted content on connection B. In the UDP model it forwards TURN ChannelData without terminating SRTP. It is generic infrastructure, not a claimed provider location.',
  },
  {
    name: 'Recipient ISP',
    short: 'ISP · US',
    lat: 41,
    lon: -80,
    h: 0.07,
    ip: '203.0.113.81',
    role: 'Provider router',
    text: 'This is the separate onward path from the relay toward the recipient’s public NAT address. TCP packets are for an existing client-initiated connection, not unsolicited inbound connections.',
  },
  {
    name: 'Recipient gateway',
    short: 'US GATEWAY',
    lat: 40.71,
    lon: -74.01,
    h: 0.14,
    ip: '203.0.113.80',
    role: 'NAT / filtering',
    text: 'An established mapping turns destination 203.0.113.80:63002 into 192.168.0.30:51821. The public IP alone cannot distinguish the recipient’s phone from other devices at home.',
  },
  {
    name: 'Their phone',
    short: 'NEW YORK',
    lat: 40.71,
    lon: -74.01,
    h: 0.29,
    ip: '192.168.0.30',
    role: 'Recipient socket + decryption',
    text: 'The OS delivers data to the matching transport socket. TCP releases bytes in order; TLS authenticates and decrypts records. The application then verifies and decrypts the end-to-end payload. A transport ACK does not mean the person read the message.',
  },
];
