import type { TraceBuilder } from "../shared/createTraceBuilder";
import { sourceLine } from "./lessonSource";

export const traceFileRequest = (trace: TraceBuilder): void => {
  trace.setActivePhase("poll");
  trace.recordSnapshot("wait-file", sourceLine("readFile"), "Poll waits for I/O", "Priority queues are empty. Native file work can progress while JavaScript has no frame to execute.");
  trace.removeToken("file-work");
  trace.placeToken("file-callback", "fs.readFile callback", "poll-queue");
  trace.recordSnapshot("file-ready", sourceLine("readFile"), "File completion makes its callback ready", "The worker reports completion to libuv. The file callback waits in poll until selected.");
  trace.enterCall("file-callback", "fs.readFile callback", sourceLine("readFile"), "Move the ready callback from poll to the call stack. Its first console.log is a separate call.");
  trace.writeConsole("file-ready", "file ready", sourceLine("logFileReady"));
  trace.scheduleCallback("file-next-tick", "file nextTick callback", "process.nextTick()", "next-tick-queue", sourceLine("scheduleFileNextTick"), "The callback waits for the current JavaScript execution to return, then nextTick runs before V8 microtasks.");
  trace.scheduleCallback("file-promise", "file Promise callback", "Promise.resolve().then()", "microtask-queue", sourceLine("scheduleFilePromise"), "The already-fulfilled Promise queues its handler in V8. It cannot interrupt the file callback.");
  trace.scheduleCallback("file-immediate", "file setImmediate callback", "setImmediate()", "check-queue", sourceLine("scheduleImmediate"), "Store this callback for the check phase after poll. It does not run during setImmediate().");
  trace.scheduleCallback("file-timer", "file timer: threshold pending", "setTimeout()", "node-timers", sourceLine("scheduleTimer"), "Register the timer with Node. Its minimum delay must elapse, and its callback still needs a turn in timers.");
  trace.enterCall("address", "server.address()", sourceLine("readPort"), "Read the assigned local port synchronously so Axios can connect to this server.");
  trace.returnFromCall("address", "server.address()", sourceLine("readPort"));
  trace.recordSnapshot("define-request-user", sourceLine("defineRequestUser"), "Define requestUser", "Creating an async function does not execute its body. The next statement calls it.");
  trace.enterCall("request-user", "requestUser()", sourceLine("callRequestUser"), "An async function starts synchronously, nested inside the file callback, until it reaches a suspending await.");
  trace.enterCall("axios-get", "axios.get()", sourceLine("awaitAxios"), "Axios starts an HTTP request and returns a Promise. Its internal setup is grouped into this frame.");
  trace.placeToken("axios-socket", "local HTTP connection", "operating-system");
  trace.recordSnapshot("open-http", sourceLine("awaitAxios"), "Hand network work to the operating system", "The OS handles socket readiness. Network I/O is not a file-system worker-pool job.");
  trace.returnFromCall("axios-get", "axios.get()", sourceLine("awaitAxios"));
  trace.removeToken("request-user");
  trace.recordSnapshot("await-axios", sourceLine("awaitAxios"), "Suspend requestUser at await", "The Axios Promise is pending. requestUser leaves the stack; its continuation is not queued until the Promise settles. The file callback resumes underneath.");
  trace.returnFromCall("file-callback", "fs.readFile callback", sourceLine("endFileCallback"));
  trace.setActivePhase(null);
  trace.recordSnapshot("file-checkpoint", sourceLine("endFileCallback"), "Checkpoint: nextTick before microtasks", "Both priority queues contain work. Node must drain them before returning to the libuv phases.");
  trace.runLoggingCallback("file-next-tick", "file nextTick callback", "file nextTick", sourceLine("scheduleFileNextTick"));
  trace.runLoggingCallback("file-promise", "file Promise callback", "file promise", sourceLine("scheduleFilePromise"));
  trace.setActivePhase("check");
  trace.recordSnapshot("select-check", sourceLine("scheduleImmediate"), "Check selects the immediate callback", "Priority work is finished. The immediate scheduled inside the file I/O callback runs in check before its timer.");
  trace.runLoggingCallback("file-immediate", "file setImmediate callback", "file immediate", sourceLine("scheduleImmediate"));
  trace.setActivePhase(null);
  trace.recordSnapshot("immediate-checkpoint", sourceLine("scheduleImmediate"), "Checkpoint: both priority queues are empty", "The immediate returned without scheduling priority work. Node can continue around the loop.");
  trace.setActivePhase("timers");
  trace.placeToken("file-timer", "file timer callback", "timers-queue");
  trace.recordSnapshot("timer-ready", sourceLine("scheduleTimer"), "The timer threshold has passed", "In this illustrated run, the timer becomes eligible before the server request handler runs. Network versus timer timing can vary between executions.");
  trace.runLoggingCallback("file-timer", "file timer callback", "file timer", sourceLine("scheduleTimer"));
  trace.setActivePhase(null);
  trace.recordSnapshot("timer-checkpoint", sourceLine("scheduleTimer"), "Checkpoint after the timer", "No nextTicks or microtasks were added by the timer. The local HTTP connection can supply the next work.");
};
