import type { LessonDefinition } from "../domain/simulation/types";

const syncOutput = { id: "sync-output", value: "sync" } as const;
const scriptEndOutput = { id: "script-end-output", value: "script end" } as const;
const awaitContinuation = { id: "await-continuation", label: "run continuation", location: "microtask-queue" } as const;
const timeoutCallback = { id: "timeout-callback", label: "timeout callback", location: "timers-queue" } as const;

export const microtaskLesson: LessonDefinition = {
  id: "microtasks-before-timers",
  title: "await resumes through the microtask queue",
  level: "intermediate",
  focus: "queues",
  description: "Go deeper by following an async function from its synchronous start through suspension, resumption, and timer execution.",
  takeaway: "After the current JavaScript operation, Promise and await microtasks run before eligible timers.",
  sourceCode: ["async function run() {", "  console.log('sync');", "  await Promise.resolve();", "  console.log('after await');", "}", "run();", "setTimeout(() => console.log('timeout'), 0);", "console.log('script end');"],
  snapshots: [
    { id: "load-main", transitionTitle: "Node loads the main module", activeLineNumber: 1, tokens: [{ id: "main", label: "main module", location: "call-stack" }], consoleEntries: [], activePhase: null, explanation: "Execution starts with the complete script on the call stack." },
    { id: "declare-run", transitionTitle: "Declare the async function", activeLineNumber: 1, tokens: [{ id: "main", label: "main module", location: "call-stack" }], consoleEntries: [], activePhase: null, explanation: "Node creates the run function. Its body does not execute until run() is called." },
    { id: "call-run", transitionTitle: "Call run()", activeLineNumber: 6, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "run", label: "run()", location: "call-stack" }], consoleEntries: [], activePhase: null, explanation: "An async function starts synchronously, so run enters the call stack immediately." },
    { id: "call-sync-log", transitionTitle: "Call console.log('sync')", activeLineNumber: 2, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "run", label: "run()", location: "call-stack" }, { id: "sync-log", label: "console.log('sync')", location: "call-stack" }], consoleEntries: [], activePhase: null, explanation: "Code before the first await behaves like ordinary synchronous JavaScript." },
    { id: "print-sync", transitionTitle: "Print sync and return", activeLineNumber: 3, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "run", label: "run()", location: "call-stack" }], consoleEntries: [syncOutput], activePhase: null, explanation: "console.log returns to run, which reaches the await expression." },
    { id: "evaluate-await", transitionTitle: "Evaluate Promise.resolve()", activeLineNumber: 3, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "run", label: "run()", location: "call-stack" }, { id: "promise-resolve", label: "Promise.resolve()", location: "call-stack" }], consoleEntries: [syncOutput], activePhase: null, explanation: "The Promise is already fulfilled, but await still yields instead of continuing synchronously." },
    { id: "suspend-run", transitionTitle: "Suspend run and queue its continuation", activeLineNumber: 3, tokens: [{ id: "main", label: "main module", location: "call-stack" }, awaitContinuation], consoleEntries: [syncOutput], activePhase: null, explanation: "run leaves the stack. V8 places the code after await in the microtask queue." },
    { id: "call-timeout", transitionTitle: "Call setTimeout(..., 0)", activeLineNumber: 7, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "set-timeout", label: "setTimeout(..., 0)", location: "call-stack" }, awaitContinuation], consoleEntries: [syncOutput], activePhase: null, explanation: "The main module continues and registers the timer after the microtask was queued." },
    { id: "register-timer", transitionTitle: "Register the timer threshold", activeLineNumber: 7, tokens: [{ id: "main", label: "main module", location: "call-stack" }, awaitContinuation, { id: "timer-wait", label: "timer · minimum 1 ms", location: "node-timers" }], consoleEntries: [syncOutput], activePhase: null, explanation: "Node registers a minimum timer threshold. A zero delay is clamped to 1 ms and does not mean immediately." },
    { id: "call-script-end", transitionTitle: "Call console.log('script end')", activeLineNumber: 8, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "end-log", label: "console.log('script end')", location: "call-stack" }, awaitContinuation, { id: "timer-wait", label: "timer · minimum 1 ms", location: "node-timers" }], consoleEntries: [syncOutput], activePhase: null, explanation: "Synchronous work continues while the microtask waits and the timer threshold is tracked." },
    { id: "finish-main", transitionTitle: "Print script end and finish the module", activeLineNumber: 8, tokens: [awaitContinuation, { id: "timer-wait", label: "timer · minimum 1 ms", location: "node-timers" }], consoleEntries: [syncOutput, scriptEndOutput], activePhase: null, explanation: "The current JavaScript operation is complete. Node drains its priority queues before continuing the event loop." },
    { id: "timer-ready", transitionTitle: "The timeout callback becomes eligible", activeLineNumber: 7, tokens: [awaitContinuation, timeoutCallback], consoleEntries: [syncOutput, scriptEndOutput], activePhase: null, explanation: "This walkthrough assumes the minimum timer threshold has now elapsed. The timeout callback waits in the timers queue while the await continuation is still queued as a microtask." },
    { id: "select-microtask", transitionTitle: "Drain the microtask queue", activeLineNumber: 4, tokens: [{ id: "await-continuation", label: "run continuation", location: "call-stack" }, timeoutCallback], consoleEntries: [syncOutput, scriptEndOutput], activePhase: null, explanation: "Even though the timer is ready, Node runs the already-queued await continuation before selecting a callback from an event-loop phase." },
    { id: "call-await-log", transitionTitle: "Call console.log('after await')", activeLineNumber: 4, tokens: [{ id: "await-continuation", label: "run continuation", location: "call-stack" }, { id: "await-log", label: "console.log('after await')", location: "call-stack" }, timeoutCallback], consoleEntries: [syncOutput, scriptEndOutput], activePhase: null, explanation: "The resumed async function performs its remaining synchronous work. The ready timer remains queued and cannot interrupt it." },
    { id: "finish-microtask", transitionTitle: "Print after await and complete run", activeLineNumber: 4, tokens: [timeoutCallback], consoleEntries: [syncOutput, scriptEndOutput, { id: "await-output", value: "after await" }], activePhase: null, explanation: "The await continuation is complete. With the microtask queue empty, Node can now continue to the timers phase." },
    { id: "select-timer", transitionTitle: "Select the ready timer callback", activeLineNumber: 7, tokens: [{ id: "timeout-callback", label: "console.log('timeout')", location: "call-stack" }], consoleEntries: [syncOutput, scriptEndOutput, { id: "await-output", value: "after await" }], activePhase: "timers", explanation: "With priority queues empty, the timers phase moves its callback to the stack." },
    { id: "complete", transitionTitle: "Print timeout and complete", activeLineNumber: 7, tokens: [], consoleEntries: [syncOutput, scriptEndOutput, { id: "await-output", value: "after await" }, { id: "timeout-output", value: "timeout" }], activePhase: "timers", explanation: "Final order: sync, script end, after await, timeout." },
  ],
};
