import type { LessonDefinition } from "../domain/simulation/types";

const startOutput = { id: "start-output", value: "start" } as const;
const endOutput = { id: "end-output", value: "end" } as const;
const nextTickTask = { id: "next-tick", label: "nextTick callback", location: "next-tick-queue" } as const;
const promiseTask = { id: "promise", label: "Promise.then callback", location: "microtask-queue" } as const;
const immediateTask = { id: "immediate", label: "setImmediate callback", location: "check-queue" } as const;

export const nextTickLesson: LessonDefinition = {
  id: "next-tick-before-promise",
  title: "In CommonJS, nextTick runs before Promise microtasks",
  level: "intermediate",
  focus: "next-tick",
  description: "Use a CommonJS entry script to compare Node's nextTick queue with V8 microtasks and the check phase.",
  takeaway: "In a CommonJS entry script, Node drains nextTick callbacks before Promise microtasks.",
  sourceCode: ["console.log('start');", "process.nextTick(() => console.log('nextTick'));", "Promise.resolve().then(() => console.log('promise'));", "setImmediate(() => console.log('immediate'));", "console.log('end');"],
  snapshots: [
    { id: "load-main", transitionTitle: "Node loads the main module", activeLineNumber: 1, tokens: [{ id: "main", label: "main module", location: "call-stack" }], consoleEntries: [], activePhase: null, explanation: "All top-level code begins as one main-module task." },
    { id: "call-start-log", transitionTitle: "Call console.log('start')", activeLineNumber: 1, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "start-log", label: "console.log('start')", location: "call-stack" }], consoleEntries: [], activePhase: null, explanation: "The first synchronous function is pushed onto the stack." },
    { id: "print-start", transitionTitle: "Print start and return", activeLineNumber: 2, tokens: [{ id: "main", label: "main module", location: "call-stack" }], consoleEntries: [startOutput], activePhase: null, explanation: "console.log returns and the main module continues." },
    { id: "call-next-tick", transitionTitle: "Call process.nextTick", activeLineNumber: 2, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "next-tick-call", label: "process.nextTick(...)", location: "call-stack" }], consoleEntries: [startOutput], activePhase: null, explanation: "process.nextTick is a normal synchronous function call. It enters the call stack to register a callback." },
    { id: "schedule-next-tick", transitionTitle: "Queue the nextTick callback", activeLineNumber: 2, tokens: [{ id: "main", label: "main module", location: "call-stack" }, nextTickTask], consoleEntries: [startOutput], activePhase: null, explanation: "Registration returns, and Node places only the supplied callback in its dedicated next-tick queue." },
    { id: "evaluate-promise-chain", transitionTitle: "Evaluate Promise.resolve().then(...)", activeLineNumber: 3, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "promise-chain", label: "Promise.resolve().then(...)", location: "call-stack" }, nextTickTask], consoleEntries: [startOutput], activePhase: null, explanation: "JavaScript evaluates the Promise expression synchronously. The nextTick callback remains waiting while the current script is still running." },
    { id: "resolve-promise", transitionTitle: "Register the Promise.then handler", activeLineNumber: 3, tokens: [{ id: "main", label: "main module", location: "call-stack" }, nextTickTask, promiseTask], consoleEntries: [startOutput], activePhase: null, explanation: "The Promise is already fulfilled, so V8 queues the then handler as a microtask. It does not execute the handler yet." },
    { id: "call-set-immediate", transitionTitle: "Call setImmediate", activeLineNumber: 4, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "set-immediate-call", label: "setImmediate(...)", location: "call-stack" }, nextTickTask, promiseTask], consoleEntries: [startOutput], activePhase: null, explanation: "setImmediate is called synchronously on the stack. Its callback has not executed and is not on the stack." },
    { id: "schedule-immediate", transitionTitle: "Queue the setImmediate callback", activeLineNumber: 4, tokens: [{ id: "main", label: "main module", location: "call-stack" }, nextTickTask, promiseTask, immediateTask], consoleEntries: [startOutput], activePhase: null, explanation: "The setImmediate call returns after Node registers its callback for a future check phase." },
    { id: "call-end-log", transitionTitle: "Call console.log('end')", activeLineNumber: 5, tokens: [{ id: "main", label: "main module", location: "call-stack" }, { id: "end-log", label: "console.log('end')", location: "call-stack" }, nextTickTask, promiseTask, immediateTask], consoleEntries: [startOutput], activePhase: null, explanation: "Top-level synchronous work still has priority." },
    { id: "finish-main", transitionTitle: "Print end and finish the CommonJS module", activeLineNumber: 5, tokens: [nextTickTask, promiseTask, immediateTask], consoleEntries: [startOutput, endOutput], activePhase: null, explanation: "The CommonJS entry operation is complete with callbacks waiting in three different queues." },
    { id: "select-next-tick", transitionTitle: "Drain the nextTick queue", activeLineNumber: 2, tokens: [{ id: "next-tick", label: "console.log('nextTick')", location: "call-stack" }, promiseTask, immediateTask], consoleEntries: [startOutput, endOutput], activePhase: null, explanation: "After a CommonJS top-level operation, Node drains the nextTick queue before V8 microtasks." },
    { id: "finish-next-tick", transitionTitle: "Print nextTick and return", activeLineNumber: 2, tokens: [promiseTask, immediateTask], consoleEntries: [startOutput, endOutput, { id: "next-tick-output", value: "nextTick" }], activePhase: null, explanation: "The nextTick queue is empty. Node immediately drains the V8 microtask queue next." },
    { id: "select-promise", transitionTitle: "Drain the Promise microtask queue", activeLineNumber: 3, tokens: [{ id: "promise", label: "console.log('promise')", location: "call-stack" }, immediateTask], consoleEntries: [startOutput, endOutput, { id: "next-tick-output", value: "nextTick" }], activePhase: null, explanation: "The Promise handler runs before Node continues into an event-loop phase." },
    { id: "finish-promise", transitionTitle: "Print promise and return", activeLineNumber: 3, tokens: [immediateTask], consoleEntries: [startOutput, endOutput, { id: "next-tick-output", value: "nextTick" }, { id: "promise-output", value: "promise" }], activePhase: null, explanation: "Both priority queues are empty, so Node may continue through the event loop." },
    { id: "select-immediate", transitionTitle: "Enter check and run setImmediate", activeLineNumber: 4, tokens: [{ id: "immediate", label: "console.log('immediate')", location: "call-stack" }], consoleEntries: [startOutput, endOutput, { id: "next-tick-output", value: "nextTick" }, { id: "promise-output", value: "promise" }], activePhase: "check", explanation: "The check phase moves the setImmediate callback onto the stack." },
    { id: "complete", transitionTitle: "Print immediate and complete", activeLineNumber: 4, tokens: [], consoleEntries: [startOutput, endOutput, { id: "next-tick-output", value: "nextTick" }, { id: "promise-output", value: "promise" }, { id: "immediate-output", value: "immediate" }], activePhase: "check", explanation: "Final order: start, end, nextTick, promise, immediate." },
  ],
};
